version: '3.8'

services:
    web-database:
        image: mysql
        container_name: web-database
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: ecommerce
        ports:
            - "3307:3307"

    web-backend:
        working_dir: /web
        container_name: web-backend
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - "3000:3000"
        depends_on:
            - web-database
        env_file:
            - .env
        # command: ['node', 'dist/server/app.js']